---
language: node_js

node_js:
  - "7.6"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - echo "Starting testrpc" && npm run testrpc > /dev/null &
  - sleep 10
  - echo "Starting oraclize" && npm run oraclize > /dev/null &
  - sleep 120

script:
  - npm test
